services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

  app:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/quiz
      - JWT_SECRET=replace-this-secret
      - NUM_QUESTIONS=4
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis
    networks:
      - mynetwork

volumes:
  mongo-data:
  redis_data:

networks:
  mynetwork:
